<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2 setup script
 * Date: Thu, 12 Jul 2012 16:29:24 -0400
 */

/* Servers configuration */
$i = 0;

/* Server: Santa Rosa [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Santa Rosa';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4fff33808b2ad7.44164086';
$cfg['DefaultLang'] = 'pt_BR';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>